Repository EAT-SSU/Server, pull requests merged in 2025-02, with the labels that each got.

#111 [Docs] README에 기초적인 문서 작성
  .github/README.md
Labels: docs

#109 Feat: 리뷰 v2 api 구현
  src/main/generated/ssu/eatssu/domain/menu/entity/QMenu.java
  src/main/generated/ssu/eatssu/domain/review/entity/QReview.java
  src/main/generated/ssu/eatssu/domain/review/entity/QReviewMenuLike.java
  src/main/java/ssu/eatssu/domain/auth/infrastructure/SecurityConfig.java
  src/main/java/ssu/eatssu/domain/menu/entity/Menu.java
  src/main/java/ssu/eatssu/domain/menu/persistence/MealMenuRepository.java
  src/main/java/ssu/eatssu/domain/menu/persistence/MealRepository.java
  src/main/java/ssu/eatssu/domain/review/dto/CreateMealReviewRequest.java
  src/main/java/ssu/eatssu/domain/review/dto/MealReviewResponse.java
  src/main/java/ssu/eatssu/domain/review/dto/MenuLikeRequest.java
  src/main/java/ssu/eatssu/domain/review/dto/RestaurantReviewResponse.java
  src/main/java/ssu/eatssu/domain/review/dto/ReviewRatingCount.java
  src/main/java/ssu/eatssu/domain/review/dto/UpdateMealReviewRequest.java
  src/main/java/ssu/eatssu/domain/review/entity/Review.java
  src/main/java/ssu/eatssu/domain/review/entity/ReviewLike.java
  src/main/java/ssu/eatssu/domain/review/entity/ReviewMenuLike.java
  src/main/java/ssu/eatssu/domain/review/presentation/MealReviewController.java
  src/main/java/ssu/eatssu/domain/review/presentation/ReviewController.java
  src/main/java/ssu/eatssu/domain/review/repository/ReviewLikeRepository.java
  src/main/java/ssu/eatssu/domain/review/repository/ReviewMenuLikeRepository.java
  src/main/java/ssu/eatssu/domain/review/repository/ReviewRepository.java
  src/main/java/ssu/eatssu/domain/review/service/MealReviewService.java
  src/main/java/ssu/eatssu/domain/slice/dto/SliceResponse.java
  src/main/java/ssu/eatssu/domain/user/dto/MyMealReviewResponse.java
  src/main/java/ssu/eatssu/domain/user/entity/User.java
  src/main/java/ssu/eatssu/domain/user/presentation/UserController.java
  src/main/java/ssu/eatssu/domain/user/service/UserService.java
  src/main/java/ssu/eatssu/domain/user/util/UserAliasUtil.java
  src/test/java/ssu/eatssu/domain/report/service/ReportServiceTest.java
  src/test/java/ssu/eatssu/domain/review/service/ReviewServiceTest.java
Labels: feat

#116 fix: 잘못된 패키지 경로 수정
  src/main/java/ssu/eatssu/global/config/S3Config.java
Labels: fix

#119 feat: 학과 기입 여부 체크 & 조회 API 구현
  src/main/java/ssu/eatssu/domain/user/dto/DepartmentResponse.java
  src/main/java/ssu/eatssu/domain/user/presentation/UserController.java
  src/main/java/ssu/eatssu/domain/user/service/UserService.java
Labels: feat

#120 refactor: generated 파일 추적 제거
  .github/README.md
  .gitignore
  build.gradle
  src/main/generated/ssu/eatssu/domain/inquiry/entity/QInquiry.java
  src/main/generated/ssu/eatssu/domain/menu/entity/QMeal.java
  src/main/generated/ssu/eatssu/domain/menu/entity/QMealMenu.java
  src/main/generated/ssu/eatssu/domain/menu/entity/QMenu.java
  src/main/generated/ssu/eatssu/domain/menu/entity/QMenuCategory.java
  src/main/generated/ssu/eatssu/domain/partnership/entity/QPartnership.java
  src/main/generated/ssu/eatssu/domain/partnership/entity/QPartnershipCollege.java
  src/main/generated/ssu/eatssu/domain/partnership/entity/QPartnershipDepartment.java
  src/main/generated/ssu/eatssu/domain/partnership/entity/QPartnershipLike.java
  src/main/generated/ssu/eatssu/domain/rating/entity/QRatings.java
  src/main/generated/ssu/eatssu/domain/review/entity/QReport.java
  src/main/generated/ssu/eatssu/domain/review/entity/QReview.java
  src/main/generated/ssu/eatssu/domain/review/entity/QReviewImage.java
  src/main/generated/ssu/eatssu/domain/review/entity/QReviewLike.java
  src/main/generated/ssu/eatssu/domain/review/entity/QReviewMenuLike.java
  src/main/generated/ssu/eatssu/domain/review/entity/QReviews.java
  src/main/generated/ssu/eatssu/domain/user/department/entity/QCollege.java
  src/main/generated/ssu/eatssu/domain/user/department/entity/QDepartment.java
  src/main/generated/ssu/eatssu/domain/user/entity/QBaseTimeEntity.java
  src/main/generated/ssu/eatssu/domain/user/entity/QUser.java
  src/main/java/ssu/eatssu/global/handler/GlobalExceptionHandler.java
Labels: refactoring
