Repository EAT-SSU/Server, pull requests merged in 2025-06, with the labels that each got.

#157 feat: 500에러, 400에러 #서버-에러 채널에 슬랫봇 알림 추가
  src/main/java/ssu/eatssu/domain/slack/entity/SlackChannel.java
  src/main/java/ssu/eatssu/domain/slack/entity/SlackMessageFormat.java
  src/main/java/ssu/eatssu/domain/slack/service/SlackService.java
  src/main/java/ssu/eatssu/global/handler/GlobalExceptionHandler.java
Labels: feat

#158 chore: AI 가이드라인 제거
  .gitignore
  .junie/guidelines.md
Labels: chore

#165 feat: 사용자 닉네임 제한 기능 추가
  src/main/java/ssu/eatssu/domain/user/config/UserProperties.java
  src/main/java/ssu/eatssu/domain/user/service/UserService.java
  src/main/resources/application.yml
Labels: fix

#169 hotfix: 운영서버 도커 배포가 안되는 문제 해결
  .github/workflows/deploy.yml
Labels: hotfix

#171 fix: 리뷰v2 0601 수정사항
  src/main/java/ssu/eatssu/domain/auth/infrastructure/SecurityConfig.java
  src/main/java/ssu/eatssu/domain/review/dto/MealReviewResponse.java
  src/main/java/ssu/eatssu/domain/review/dto/MenuReviewsV2Response.java
  src/main/java/ssu/eatssu/domain/review/dto/ReviewRatingCount.java
  src/main/java/ssu/eatssu/domain/review/entity/Review.java
  src/main/java/ssu/eatssu/domain/review/entity/Reviews.java
  src/main/java/ssu/eatssu/domain/review/presentation/ReviewControllerV2.java
  src/main/java/ssu/eatssu/domain/review/repository/ReviewLikeRepository.java
  src/main/java/ssu/eatssu/domain/review/repository/ReviewMenuLikeRepository.java
  src/main/java/ssu/eatssu/domain/review/service/ReviewServiceV2.java
  src/main/java/ssu/eatssu/domain/slice/service/SliceService.java
  src/main/java/ssu/eatssu/domain/user/dto/MyMealReviewResponse.java
  src/main/java/ssu/eatssu/domain/user/dto/MyReviewDetail.java
  src/main/java/ssu/eatssu/domain/user/presentation/UserController.java
  src/main/java/ssu/eatssu/domain/user/util/UserAliasUtil.java
  src/main/java/ssu/eatssu/global/handler/GlobalExceptionHandler.java
Labels: feat

#178 feat: .gitignore 및 코드컨벤션에 맞는 AI Rules 작성
  .cursor/rules/eatssu-server-rule.mdc
  .github/copilot-instructions.md
  .gitignore
  CLAUDE.md
  GEMINI.md
Labels: feat

#177 feat: 테스트 코드 구조 개선 및 OAuthService 테스트 케이스 추가
  .github/copilot-instructions.md
  build.gradle
  src/main/java/ssu/eatssu/domain/auth/service/OAuthService.java
  src/main/java/ssu/eatssu/domain/user/dto/Tokens.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/ssu/eatssu/EatSsuApplicationTests.java
  src/test/java/ssu/eatssu/domain/auth/infrastructure/TestAppleAuthenticator.java
  src/test/java/ssu/eatssu/domain/auth/service/OAuthServiceTest.java
  src/test/java/ssu/eatssu/domain/auth/service/OauthServiceTest.java
  src/test/java/ssu/eatssu/domain/menu/service/MealServiceTest.java
  src/test/java/ssu/eatssu/domain/menu/service/MenuServiceTest.java
  src/test/resources/application-test.yml
  src/test/resources/application.yml
Labels: feat

#180 feat: Review 엔티티 필드 및 메서드 정리
  src/main/java/ssu/eatssu/domain/review/entity/Review.java
Labels: fix
