Repository EAT-SSU/Server, pull requests merged in 2025-09, with the labels that each got.

#216 fix: 에러 헨들러에서 500대 에러만 보내도록 수정
  src/main/java/ssu/eatssu/global/handler/GlobalExceptionHandler.java
  src/main/java/ssu/eatssu/global/handler/response/BaseResponseStatus.java
Labels: fix

#220 [Release] v2.0.4 릴리즈
  src/main/java/ssu/eatssu/domain/partnership/dto/CreatePartnershipRequest.java
  src/main/java/ssu/eatssu/domain/partnership/dto/PartnershipDetailResponse.java
  src/main/java/ssu/eatssu/domain/partnership/dto/PartnershipInfo.java
  src/main/java/ssu/eatssu/domain/partnership/entity/Partnership.java
  src/main/java/ssu/eatssu/domain/partnership/entity/PartnershipType.java
  src/main/java/ssu/eatssu/domain/partnership/entity/RestaurantType.java
Labels: hotfix

#229 fix: 총학 관련 문제 임시 해결
  src/main/java/ssu/eatssu/domain/partnership/dto/PartnershipInfo.java
  src/main/java/ssu/eatssu/domain/partnership/persistence/PartnershipRepository.java
Labels: fix

#235 fix: 쿼리 수정
  src/main/java/ssu/eatssu/domain/partnership/persistence/PartnershipRepository.java
  src/main/java/ssu/eatssu/domain/partnership/persistence/PartnershipRestaurantRepository.java
Labels: fix

#244 feat: 로깅 기능 구현
  .github/workflows/deploy.yml
  Dockerfile
  build.gradle
  src/main/java/ssu/eatssu/domain/auth/dto/AppleLoginRequest.java
  src/main/java/ssu/eatssu/domain/auth/dto/KakaoLoginRequest.java
  src/main/java/ssu/eatssu/domain/auth/dto/ValidRequest.java
  src/main/java/ssu/eatssu/domain/inquiry/dto/CreateInquiryRequest.java
  src/main/java/ssu/eatssu/domain/inquiry/service/InquiryService.java
  src/main/java/ssu/eatssu/domain/menu/presentation/dto/response/MenusInMealResponse.java
  src/main/java/ssu/eatssu/domain/menu/service/MealService.java
  src/main/java/ssu/eatssu/domain/partnership/service/PartnershipService.java
  src/main/java/ssu/eatssu/domain/report/service/ReportService.java
  src/main/java/ssu/eatssu/domain/review/service/ReviewServiceV2.java
  src/main/java/ssu/eatssu/domain/user/service/UserService.java
  src/main/java/ssu/eatssu/global/config/AsyncConfig.java
  src/main/java/ssu/eatssu/global/log/ControllerLogAspect.java
  src/main/java/ssu/eatssu/global/log/MDCLoggingFilter.java
  src/main/java/ssu/eatssu/global/log/annotation/LogMask.java
  src/main/java/ssu/eatssu/global/log/event/LogEvent.java
  src/main/java/ssu/eatssu/global/log/event/LogEventListener.java
  src/main/resources/logback-spring.xml
Labels: feat

#248 fix: 250930 수정요청사항
  src/main/java/ssu/eatssu/domain/auth/infrastructure/SecurityConfig.java
  src/main/java/ssu/eatssu/domain/auth/security/JwtAuthenticationFilter.java
  src/main/java/ssu/eatssu/domain/menu/entity/Menu.java
  src/main/java/ssu/eatssu/domain/menu/persistence/QuerydslMenuRatingCalculator.java
  src/main/java/ssu/eatssu/domain/partnership/dto/PartnershipInfo.java
  src/main/java/ssu/eatssu/domain/partnership/entity/Partnership.java
  src/main/java/ssu/eatssu/domain/partnership/persistence/PartnershipRepository.java
  src/main/java/ssu/eatssu/domain/restaurant/entity/Restaurant.java
  src/main/java/ssu/eatssu/domain/review/dto/CreateMenuReviewRequest.java
  src/main/java/ssu/eatssu/domain/review/dto/MealReviewResponse.java
  src/main/java/ssu/eatssu/domain/review/dto/MealReviewsV2Response.java
  src/main/java/ssu/eatssu/domain/review/dto/MenuReviewsV2Response.java
  src/main/java/ssu/eatssu/domain/review/dto/RestaurantReviewResponse.java
  src/main/java/ssu/eatssu/domain/review/dto/ReviewDetail.java
  src/main/java/ssu/eatssu/domain/review/dto/ValidMenuForViewResponse.java
  src/main/java/ssu/eatssu/domain/review/service/ReviewServiceV2.java
  src/main/java/ssu/eatssu/domain/review/utils/MenuFilterUtil.java
  src/main/java/ssu/eatssu/domain/user/department/entity/College.java
  src/main/java/ssu/eatssu/domain/user/department/entity/Department.java
  src/main/java/ssu/eatssu/domain/user/dto/GetDepartmentResponse.java
  src/main/java/ssu/eatssu/domain/user/dto/MyMealReviewResponse.java
  src/main/java/ssu/eatssu/domain/user/service/UserService.java
  src/main/java/ssu/eatssu/global/handler/GlobalExceptionHandler.java
  src/main/java/ssu/eatssu/global/handler/response/BaseResponseStatus.java
Labels: fix

#249 fix: 제휴 지도 & 신고 기능 수정 사항 (20250930)
  .github/workflows/deploy.yml
  .gitignore
  src/main/java/ssu/eatssu/domain/partnership/persistence/PartnershipRestaurantRepository.java
  src/main/java/ssu/eatssu/domain/report/dto/ReportCreateRequest.java
  src/main/java/ssu/eatssu/domain/report/repository/ReportRepository.java
  src/main/java/ssu/eatssu/domain/report/service/ReportService.java
  src/main/java/ssu/eatssu/domain/review/dto/ReviewDetail.java
  src/main/java/ssu/eatssu/global/handler/response/BaseResponseStatus.java
Labels: fix
