Repository EAT-SSU/Server, pull requests merged in 2025-07, with the labels that each got.

#185 cleanup: 코드 포맷팅 적용
  src/main/java/ssu/eatssu/domain/auth/entity/OAuthProvider.java
  src/main/java/ssu/eatssu/domain/auth/infrastructure/SecurityConfig.java
  src/main/java/ssu/eatssu/domain/inquiry/entity/InquiryStatus.java
  src/main/java/ssu/eatssu/domain/menu/entity/Meal.java
  src/main/java/ssu/eatssu/domain/menu/entity/Menu.java
  src/main/java/ssu/eatssu/domain/rating/entity/RatingCountMap.java
  src/main/java/ssu/eatssu/domain/report/dto/ReportTypeInformation.java
  src/main/java/ssu/eatssu/domain/review/dto/MealReviewResponse.java
  src/main/java/ssu/eatssu/domain/review/dto/MenuReviewsV2Response.java
  src/main/java/ssu/eatssu/domain/review/dto/ReviewRatingCount.java
  src/main/java/ssu/eatssu/domain/review/entity/Review.java
  src/main/java/ssu/eatssu/domain/review/entity/Reviews.java
  src/main/java/ssu/eatssu/domain/review/presentation/ReviewControllerV2.java
  src/main/java/ssu/eatssu/domain/review/repository/ReviewMenuLikeRepository.java
  src/main/java/ssu/eatssu/domain/review/service/ReviewServiceV2.java
  src/main/java/ssu/eatssu/domain/slack/entity/SlackChannel.java
  src/main/java/ssu/eatssu/domain/slice/service/SliceService.java
  src/main/java/ssu/eatssu/domain/user/dto/MyMealReviewResponse.java
  src/main/java/ssu/eatssu/domain/user/dto/MyReviewDetail.java
  src/main/java/ssu/eatssu/domain/user/dto/Tokens.java
  src/main/java/ssu/eatssu/domain/user/entity/User.java
  src/main/java/ssu/eatssu/domain/user/presentation/UserController.java
  src/main/java/ssu/eatssu/global/handler/GlobalExceptionHandler.java
  src/test/java/ssu/eatssu/domain/auth/service/OAuthServiceTest.java
Labels: cleanup

#189 feat: 250626 리뷰v2수정요청사항
  src/main/java/ssu/eatssu/domain/menu/entity/Menu.java
  src/main/java/ssu/eatssu/domain/review/dto/CreateMealReviewRequest.java
  src/main/java/ssu/eatssu/domain/review/dto/CreateMenuReviewRequest.java
  src/main/java/ssu/eatssu/domain/review/dto/MealReviewResponse.java
  src/main/java/ssu/eatssu/domain/review/dto/MealReviewsV2Response.java
  src/main/java/ssu/eatssu/domain/review/dto/MenuReviewsV2Response.java
  src/main/java/ssu/eatssu/domain/review/dto/ValidMenuForViewResponse.java
  src/main/java/ssu/eatssu/domain/review/entity/Review.java
  src/main/java/ssu/eatssu/domain/review/presentation/ReviewControllerV2.java
  src/main/java/ssu/eatssu/domain/review/service/ReviewServiceV2.java
  src/main/java/ssu/eatssu/domain/review/utils/MenuFilterUtil.java
  src/main/java/ssu/eatssu/domain/user/dto/MyMealReviewResponse.java
Labels: feat

#195 fix: 시큐리티 필터에서도 슬랙 알림 보낼 수 있게 수정
  src/main/java/ssu/eatssu/domain/auth/infrastructure/SecurityConfig.java
  src/main/java/ssu/eatssu/domain/auth/security/JwtAuthenticationFilter.java
  src/main/java/ssu/eatssu/domain/auth/security/JwtTokenProvider.java
  src/main/java/ssu/eatssu/domain/menu/entity/Meal.java
  src/main/java/ssu/eatssu/domain/menu/entity/Menu.java
  src/main/java/ssu/eatssu/domain/partnership/dto/CreatePartnershipRequest.java
  src/main/java/ssu/eatssu/domain/partnership/presentation/PartnershipController.java
  src/main/java/ssu/eatssu/domain/partnership/service/PartnershipService.java
  src/main/java/ssu/eatssu/domain/review/dto/ValidMenuForViewResponse.java
  src/main/java/ssu/eatssu/domain/review/presentation/ReviewControllerV2.java
  src/main/java/ssu/eatssu/domain/slack/entity/SlackMessageFormat.java
  src/main/java/ssu/eatssu/domain/slack/service/SlackErrorNotifier.java
  src/main/java/ssu/eatssu/domain/user/department/entity/College.java
  src/main/java/ssu/eatssu/domain/user/department/entity/Department.java
  src/main/java/ssu/eatssu/domain/user/entity/User.java
  src/main/java/ssu/eatssu/global/handler/GlobalExceptionHandler.java
  src/main/java/ssu/eatssu/global/handler/response/BaseResponseStatus.java
  src/main/resources/application-local.yml
Labels: fix

#196 feat: .env 파일 사용
  .gemini/styleguide.md
  .gitignore
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: feat

#206 feat: 식단 추가 api에 FACULTY enum추가
  src/main/java/ssu/eatssu/domain/restaurant/entity/Restaurant.java
Labels: feat

#198 fix: Java Toolchain 설정 추가 (Java 17)
  build.gradle
Labels: fix
